### ISSUE TITLE
Feature Request: Page Groups

### ISSUE THREAD

**Issue by gavinhsmith** [jcv8000/Codex#10]
A feature like page groups would allow you to make sections within a notebook. For example, if you had a class that had collections of course content within a group (unit, chapter, etc.) being able to store different notebook pages under a few groups would really help with organization.

**Comment by GMkonan** [comment]
I think creating groups as chapters are a great Idea too, since I see this app as a way of mimicking a setup where you would have physical notebooks.

**Comment by officialpiyush** [comment]
+1 for this

**Comment by jcv8000** [comment]
This will be in 2.0
