### ISSUE TITLE
Feature Request: Line spacing

### ISSUE THREAD

**Issue by codingduckAU** [jcv8000/Codex#12]
So by default your line spacing is large..... Basically like a new paragraph.
Sometimes we just want to stay on the same paragraph and just a new line.

Please allow to hold down shift while pressing enter (new line), and the cursur goes to the very next line without any major line spacing.

Thanks for the awesome app!

**Comment by dan-dx2** [comment]
After reviewing your HTML code in developer mode, seems like everytime <ENTER> is pressed, a new paragraph (<P>) is inserted.

Holding down shift while pressing enter and a <BR> is inserted would be perfect!
