### ISSUE TITLE
Unable to search 

### ISSUE THREAD

**Issue by muntazir02** [jcv8000/Codex#16]
Unable to search or find documentation on how to search for anything in the tool. I expected CTRL+F to work. 
This is a great tool, but before I start depending on it for all my snippets and notes, there has to be an easy way to search within the same notebook and across all notes. Usually other similar tools have a search box in one corner and use shortcuts CTRL+F & CTRL+E

**Comment by jcv8000** [comment]
I'm gonna be looking into some possibilities for searching notes in 2.0 (searching all notes AND searching the current page), hopefully I can get that added
