### ISSUE TITLE
Need help to build for manjaro

### ISSUE THREAD

**Issue by gonzalovsilva** [jcv8000/Codex#2]
Hi, I would like to know how can I build it to use it on linux manjaro.

**Comment by jcv8000** [comment]
I got a Manjaro VM set up and downloaded the `tar.xz` file from the Downloads page, and if you extract that with
```bash
tar -xf <filename>
```
and go into the extracted folder and run `./Codex` it seems to work fine.

---
If you want to make some change and build the project, you just have to install NodeJS and npm, clone the repository, and run
```bash
npm install
```
and then make your changes and run
```bash
npx electron-builder
```
and that seemed to work fine for me

**Comment by gonzalovsilva** [comment]
Thank you for this tool. I'll be saving my snippets from now on with this :)
