### ISSUE TITLE
Feature Request: Adding Gifs

### ISSUE THREAD

**Issue by Krillinator** [jcv8000/Codex#21]
Hello there!

I've been using codex for a while and recommend it to all of my students, due to how amazing this is!

One thing that would benefit my notes would be to record tidbits of Unreal Engine code and display an example result, and am wondering if this is something that could be added? 

All the love - Krill!

**Comment by codingduckAU** [comment]
Yeah gifs would be awesome! I tried to copy/paste one but it only showed the first frame.
