### ISSUE TITLE
I've added a code block and can't delete it

### ISSUE THREAD

**Issue by astef** [jcv8000/Codex#22]
Type three backticks - ``` , and that's it, your page is broken, you can't normally delete that thing.

**Comment by Rixxo-WX** [comment]
Works fine for me,

1. Erase all text inside the block
2. Use "Shift + Enter" to escape the block 
3. Press backspace

**Comment by astef** [comment]
Trick worked, thanks!

Still, I'd expect something simpler, like Arrow Down at the last line of the code snippet to do the same what "Shift+Enter" does
