### ISSUE TITLE
save.json error 

### ISSUE THREAD

**Issue by sabah111** [jcv8000/Codex#25]
I suddenly started getting this error and longer had access to my notes even though the notes still existed in the directory.. please advise

![image](https://user-images.githubusercontent.com/60841800/170513879-03e1fc6c-7660-415f-8d6f-625ac4c1605c.png)

**Comment by jcv8000** [comment]
Could you paste the contents of your save.json into a gist or pastebin and
send me the link?

**Comment by jcv8000** [comment]
Could you paste the contents of your save.json into a gist or pastebin and send me the link?
