### ISSUE TITLE
Building on M1 Mac

### ISSUE THREAD

**Issue by pigeontech** [jcv8000/Codex#26]
Was getting this error when using `npx electron-builder`:

```
Exit code: ENOENT. spawn /usr/bin/python ENOENT failedTask=build stackTrace=Error: Exit code: ENOENT. spawn /usr/bin/python ENOENT
```

I fixed it by changing this block in `package.json`:

```   
    "devDependencies": {
        "electron": "latest",
        "electron-builder": "latest"
    }
```

While I'm here, is there a way to exit a code block **before** and not just after? If the code block was the first thing you made, but now you want to add some text above it, how would you do that?

**Comment by williamT386** [comment]
No such error for me while building on a M1 Mac

**Comment by wetterkrank** [comment]
+1, built successfully
