### ISSUE TITLE
Bug | Export as pdf-file is not working

### ISSUE THREAD

**Issue by FoenX** [jcv8000/Codex#37]
The function to export your content as pdf-file is not working with portable linux version on Fedora 36 (Workstation Edition with Gnome 42.4).

**Comment by MarcinLebiedzinski** [comment]
I can't export on Ubuntu. Is there any solution to fix it?

**Comment by jcv8000** [comment]
> I can't export on Ubuntu. Is there any solution to fix it?

Is there any error in the Devtools console (Ctrl+Shift+i) when you try to export?
