### ISSUE TITLE
Problem Opening Application

### ISSUE THREAD

**Issue by MaherEdriss** [jcv8000/Codex#41]
Program works fine on my pc, but when I try to use it on my laptop I get the error "your preference file could not be parsed correctly". Have been using it fine on the laptop for a long time now and this is a sudden issue. Tried reinstalling but still get the same error.

**Comment by jcv8000** [comment]
Go to your `%appdata%` folder (windows) or `~/.config` (linux) or `~/Library/Application Support` on macOS and delete the `codex/prefs.json` file
