### ISSUE TITLE
Feature Request: Adding support for saving to Github Gists

### ISSUE THREAD

**Issue by praharshjain** [jcv8000/Codex#45]
It would be great to have support for saving the notes as private Github Gists.

**Comment by jcv8000** [comment]
Right now if you wanted to do this, you can

1. Right-click on your note and select "Export as MD"
2. Copy the contents of that file
3. Create a new Gist and then paste in the text you copied
4. Name the file `(something).md` to tell Gist that it's a Markdown file

Then the Gist editor will show a Preview tab of the markdown, and when you save the Gist it will show that rendered markdown too.

I don't have any plans of adding any further Gist integration right now
