### ISSUE TITLE
Markdown Table out of bounds

### ISSUE THREAD

**Issue by Gereks123** [jcv8000/Codex#55]
When using a table within my page, and storing some code examples within the table, it goes beyond the pages' lines and it looks pretty clunky. 

Here's an example:
![image](https://github.com/jcv8000/Codex/assets/66975562/b82246d3-ad4b-4b86-a068-1437bc398624)

Could this be caused by me or it is the intended design? It is not a major issue, just wanted to bring it out.

**Comment by jcv8000** [comment]
Fixed in [cd7540c](https://github.com/jcv8000/Codex/commit/cd7540cfa421813489b59ada1a270ce85ee92778), will be out in 2.0.0

Thanks for reporting this
