### ISSUE TITLE
Dark-mode: Horizontal line is not visible/discernible

### ISSUE THREAD

**Issue by dulocian** [jcv8000/Codex#61]
When in dark mode, the horizontal line does not take on the same colour as the text. Instead it remains black, which is difficult to see against the dark background. See example screenshot. **Using v2.0.1**

![Codex_pBckaJuCHm](https://github.com/jcv8000/Codex/assets/17469241/18271c7b-e39b-4332-ac1c-6bb0c9f25479)
![image](https://github.com/jcv8000/Codex/assets/17469241/199737f0-3bd0-4258-9db5-5171ec7b71a9)

**Comment by dulocian** [comment]
Similar case for the block quote. The vertical line is not discernable against the dark background.
![Codex_iBIlLmqUNg](https://github.com/jcv8000/Codex/assets/17469241/b5d6ce8c-4654-4dc6-9042-07d81aad2e53)
![Codex_Q9xzxZ9tZi](https://github.com/jcv8000/Codex/assets/17469241/2548ae1b-ee9e-4ca4-82ec-d9eabd4bf650)

**Comment by jcv8000** [comment]
Fixed in 29831a6 and c6f4b73, will be out in 2.0.3.

Thanks for letting me know about this 👍
