### ISSUE TITLE
Lost save.json file while updating

### ISSUE THREAD

**Issue by Gereks123** [jcv8000/Codex#62]
I actually did backup my `save.json` and notes folder. Somehow my save.json got replaced with the default one when installing the latest version of Codex. Now I am in a pickle.

My notes folders does show the latest changes I've made to the folders but my save.json file is totally wiped. Am i screwed?

Thanks in advance!

**Comment by Gereks123** [comment]
Just to inform, the save.json got replaced in my other TOTALLY different folder that i made myself. This might have been my own error. But that's still strange, because I did not touch the backed up folder I made.

**Comment by jcv8000** [comment]
I don't really see how the app could've overwritten the separate backup that you made

Worst case scenario, the `save.json` is just a list of all of your notebooks/pages, and the actual contents of your notes are in the `notes` folder.

So you could create a bunch of Pages in the app, or make a Notebook in the app & copy/paste a bunch of empty pages in the `save.json`
```json
"children": [
    {
        "name": "Searching & Sorting",
        "id": "bad7dcdd-7e56-4f46-9b20-e2807b34e4f9",
        "color": "#999999",
        "icon": "file-text",
        "fileName": "Searching--Sortingbad7dcdd-",
        "textContent": "",
        "favorited": false
    },
    // ^^^ copy and paste, change the ID to something unique
]
```
then go through and hook up each one of those pages in the `save.json` to the json files that are in your `notes` folder by setting the `"fileName": "..."` property in the copies

**Comment by Gereks123** [comment]
> I don't really see how the app could've overwritten the separate backup that you made
> 
> Worst case scenario, the `save.json` is just a list of all of your notebooks/pages, and the actual contents of your notes are in the `notes` folder.
> 
> So you could create a bunch of Pages in the app, or make a Notebook in the app & copy/paste a bunch of empty pages in the `save.json`
> 
> ```json
> "children": [
>     {
>         "name": "Searching & Sorting",
>         "id": "bad7dcdd-7e56-4f46-9b20-e2807b34e4f9",
>         "color": "#999999",
>         "icon": "file-text",
>         "fileName": "Searching--Sortingbad7dcdd-",
>         "textContent": "",
>         "favorited": false
>     },
>     // ^^^ copy and paste, change the ID to something unique
> ]
> ```
> 
> then go through and hook up each one of those pages in the `save.json` to the json files that are in your `notes` folder by setting the `"fileName": "..."` property in the copies

Understandable, I realize the mistake I made and that's totally on me. Thanks for the help!

**Comment by Gereks123** [comment]
> I don't really see how the app could've overwritten the separate backup that you made
> 
> Worst case scenario, the `save.json` is just a list of all of your notebooks/pages, and the actual contents of your notes are in the `notes` folder.
> 
> So you could create a bunch of Pages in the app, or make a Notebook in the app & copy/paste a bunch of empty pages in the `save.json`
> 
> ```json
> "children": [
>     {
>         "name": "Searching & Sorting",
>         "id": "bad7dcdd-7e56-4f46-9b20-e2807b34e4f9",
>         "color": "#999999",
>         "icon": "file-text",
>         "fileName": "Searching--Sortingbad7dcdd-",
>         "textContent": "",
>         "favorited": false
>     },
>     // ^^^ copy and paste, change the ID to something unique
> ]
> ```
> 
> then go through and hook up each one of those pages in the `save.json` to the json files that are in your `notes` folder by setting the `"fileName": "..."` property in the copies

Got it, generated some pages but the contents are still gone. That's totally on me, thanks for the help tho!
