### ISSUE TITLE
Copying text font size not correct

### ISSUE THREAD

**Issue by Gereks123** [jcv8000/Codex#69]
When copying text from another page that has some styling done to it, the font-size isn't displayed exactly in the correct way.

I have a page where the style is following:
![image](https://github.com/jcv8000/Codex/assets/66975562/6ca8419a-bf40-48bc-89d7-4a92d7a901ef)

Now I copy the highlighted part into another page and this happens:
![image](https://github.com/jcv8000/Codex/assets/66975562/c4071ddd-8880-48de-aa31-e37f04995cff)

The editor shows the correct style, but the font-size is not exactly right. 
On the second picture you can also see that the "font-size" box has another "px" concated to it. Could that be the issue? 

OS: Windows 11
Codex Version: 2.0.2 (latest)

**Comment by jcv8000** [comment]
Fixed in b424663, will be out in 2.0.3

Thanks for reporting 👍
