### ISSUE TITLE
Pages should not be saved everytime, causing lost data in high latency environments.

### ISSUE THREAD

**Issue by Stump8743** [jcv8000/Codex#72]
The pages should not be saving every time they are viewed. 

**I have lost a few pages content thanks to latency when running Codex via a SSHFS mounted remote disk to share with other people.** 

The solution is to:

1. Only save data when it is changed e.g. compare of checksum on load and again when navigating away from the page to only save when data has changed.

2. Have a read-only and write mode. You must put Codex in write mode to make changes.

3. Make saving the responsibility of the user via a save button.

**Comment by jcv8000** [comment]
I'll get right on this for the next patch, thanks for letting me know

**Comment by jcv8000** [comment]
Just released 2.0.4 which has a setting for "Autosave pages when switching between pages" which you'd want to disable.

Now it will keep track of whether you've made any changes to the page. If you switch pages with no changes it won't overwrite anything, if you do have unsaved changes it will make a popup asking to save/discard the changes or go back
