### ISSUE TITLE
how to open exported files?

### ISSUE THREAD

**Issue by iqsalah** [jcv8000/Codex#82]
the software is cool.
but how can I open the file that I exported as MD file?

**Comment by jcv8000** [comment]
The exported Markdown is just a text file. If you wanted to upload/post your notes to a different website that supports Markdown in its editor like GitHub or Reddit you could copy/paste that

**Comment by iqsalah** [comment]
> The exported Markdown is just a text file. If you wanted to upload/post your notes to a different website that supports Markdown in its editor like GitHub or Reddit you could copy/paste that

I want to open the same MD file that I exported from "Codex" on another laptop with the same structure and shape of MD file in "Codex", that is my problem.
