### ISSUE TITLE
"Other" syntax highlighting is seemingly broken.

### ISSUE THREAD

**Issue by RattleyCooper** [jcv8000/Codex#9]
While I'm trying to use this app for the Nim language I'm having issues with the syntax highlighting along with the app locking up or replacing code when I hit the return key.

The app locking up is a major bummer because it's not just a second or 2.  It's a full 10-15 seconds whenever I start a new code block and start typing.  I had an entire block of code written out and when I clicked back into the code block to add a comment, the app locked up for about 15 seconds and erased all of my code after the spot where I started typing my comment.

Edit:  Control + Z does not recover the lost data

**Comment by jcv8000** [comment]
Thank you for letting me know about this

Just fixed this in this commit: 2ce04c163c3972f89501276a3e212f64f7f373bc

1.4.1 should be out shortly to fix it.
